Simplification changes:
1. All scripts use process_arguments to process arguments
2. Don't try to differentiate build modifiers (pass them down, valid or not)
3. Support passing VERBOSE down.
4. Support a DESTDIR variable.
5. Default installation place is now $LLVM_TOP/installed.
6. Add two scripts: clean and install, with the obvious actions.
7. Put build_a_module in the library so it can be used by "install"

llvm-svn: 40086

diff --git a/llvm-top/clean b/llvm-top/clean
--- a/llvm-top/clean
+++ b/llvm-top/clean
@@ -12,18 +12,10 @@
 
 . ./library.sh
 
-# Get the list of modules. Either everything checked out or the list passed in.
-if test -z "$*" ; then
-  MODULES=""
-  for modinfo in */ModuleInfo.txt ; do
-    mod=`dirname $modinfo`
-    mod=`basename $modinfo`
-    MODULES="$mod $MODULES"
-  done
-else
-  MODULES="$*"
-fi
+# Get the list of modules.
+process_arguments "$@"
 
+# Get the 
 get_module_dependencies $MODULES
 
 for mod in $MODULE_DEPENDENCIES ; do
@@ -31,9 +23,8 @@ for mod in $MODULE_DEPENDENCIES ; do
   if test ! -z "$MODULE_INFO_VALUE" ; then
     msg 0 Cleaning module $mod
     cd $mod
-    $MODULE_INFO_VALUE
-    cd ..
+    $MODULE_INFO_VALUE || die $? "Clean of module $mod failed."
   else
-    msg 0 Module $mod has no CleanCmd
+    msg 0 Module $mod has no CleanCmd in the ModuleInfo.txt
   fi
 done
