Regenate configure
llvm-svn: 18619

diff --git a/java/configure b/java/configure
--- a/java/configure
+++ b/java/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='Java 0.0'
 PACKAGE_BUGREPORT='llvmbugs@cs.uiuc.edu'
 
 ac_unique_file="Makefile.common.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS JIKES JAVAC JAVA LLVM_SRC LLVM_OBJ LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS JAVAC JAVA LLVM_SRC LLVM_OBJ LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -715,6 +715,14 @@ ac_env_target_alias_set=${target_alias+set}
 ac_env_target_alias_value=$target_alias
 ac_cv_env_target_alias_set=${target_alias+set}
 ac_cv_env_target_alias_value=$target_alias
+ac_env_JAVAC_set=${JAVAC+set}
+ac_env_JAVAC_value=$JAVAC
+ac_cv_env_JAVAC_set=${JAVAC+set}
+ac_cv_env_JAVAC_value=$JAVAC
+ac_env_JAVA_set=${JAVA+set}
+ac_env_JAVA_value=$JAVA
+ac_cv_env_JAVA_set=${JAVA+set}
+ac_cv_env_JAVA_value=$JAVA
 
 #
 # Report the --help message.
@@ -789,6 +797,13 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-llvmsrc          Location of LLVM Source Code
   --with-llvmobj          Location of LLVM Object Code
+
+Some influential environment variables:
+  JAVAC       The java compiler (used for testing)
+  JAVA        The Java Virtual Machine (used for testing)
+
+Use these variables to override the choices made by `configure' or to help
+it to find libraries and programs with nonstandard names/locations.
 
 Report bugs to <llvmbugs@cs.uiuc.edu>.
 _ACEOF
@@ -1309,40 +1324,6 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 
 
-# Extract the first word of "jikes", so it can be a program name with args.
-set dummy jikes; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_JIKES+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$JIKES"; then
-  ac_cv_prog_JIKES="$JIKES" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_JIKES="jikes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-JIKES=$ac_cv_prog_JIKES
-if test -n "$JIKES"; then
-  echo "$as_me:$LINENO: result: $JIKES" >&5
-echo "${ECHO_T}$JIKES" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
 
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
@@ -1379,6 +1360,7 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+
 # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -1414,6 +1396,18 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+
+if test -z "$JAVA"
+then
+  { echo "$as_me:$LINENO: WARNING: A Java Virtual Machine is required for the test suite, but it was not found" >&5
+echo "$as_me: WARNING: A Java Virtual Machine is required for the test suite, but it was not found" >&2;}
+fi
+
+if test -z "$JAVAC"
+then
+  { echo "$as_me:$LINENO: WARNING: A Java compiler is required for the test suite, but it was not found" >&5
+echo "$as_me: WARNING: A Java compiler is required for the test suite, but it was not found" >&2;}
+fi
 
 
 
@@ -2115,7 +2109,6 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
-s,@JIKES@,$JIKES,;t t
 s,@JAVAC@,$JAVAC,;t t
 s,@JAVA@,$JAVA,;t t
 s,@LLVM_SRC@,$LLVM_SRC,;t t
