[llvm-gcc4-conversion-from-apple-mirror @ 299] auto-merge 2007-03-30T02:00:01-0700
Original author: bwendlin
Date: 2007-03-30 09:02:21.558544+00:00

llvm-svn: 40295

diff --git a/llvm-gcc-4.0/build_gcc b/llvm-gcc-4.0/build_gcc
--- a/llvm-gcc-4.0/build_gcc
+++ b/llvm-gcc-4.0/build_gcc
@@ -244,7 +244,9 @@ if [ \! -f Makefile ]; then
    `if [ $BUILD = i686 ] ; then echo $I386_CPU ; fi` \
    --host=$BUILD-apple-darwin$DARWIN_VERS --target=$BUILD-apple-darwin$DARWIN_VERS || exit 1
 fi
-make $MAKEFLAGS $BOOTSTRAP CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
+# Unset RC_DEBUG_OPTIONS because it causes the bootstrap to fail.
+RC_DEBUG_OPTIONS= \
+  make $MAKEFLAGS $BOOTSTRAP CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
 make $MAKEFLAGS html CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
 make $MAKEFLAGS DESTDIR=$DIR/dst-$BUILD-$BUILD install-gcc install-target \
   CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
