Regenerate.
llvm-svn: 109068

diff --git a/llvm-gcc-4.2/gcc/configure b/llvm-gcc-4.2/gcc/configure
--- a/llvm-gcc-4.2/gcc/configure
+++ b/llvm-gcc-4.2/gcc/configure
@@ -16837,11 +16837,8 @@ foo:	.long	25
 	tls_first_major=2
 	tls_first_minor=17
 	;;
-  i[34567]86-*-darwin*)
-    conftest_s='.tbss _a,4,2'
-    tls_first_major=0
-    tls_first_minor=0
-    ;;
+	i[34567]86-*-darwin*)
+	;;
   i[34567]86-*-*)
     conftest_s='
 	.section ".tdata","awT",@progbits
@@ -16862,11 +16859,8 @@ foo:	.long	25
 	tls_first_minor=14
 	tls_as_opt=--fatal-warnings
 	;;
-  x86_64-*-darwin*)
-    conftest_s='.tbss _a,4,2'
-    tls_first_major=0
-    tls_first_minor=0
-    ;;
+	x86_64-*-darwin*)
+	;;
   x86_64-*-*)
     conftest_s='
 	.section ".tdata","awT",@progbits
@@ -17141,6 +17135,83 @@ if test $gcc_cv_as_tls = yes; then
   set_have_as_tls=yes
 fi
 fi
+# Linker test for tls.
+case "$target" in
+  *-*-darwin*)
+    { echo "$as_me:$LINENO: checking darwin linker tls support" >&5
+echo $ECHO_N "checking darwin linker tls support... $ECHO_C" >&6; }
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char _tlv_bootstrap ();
+int
+main ()
+{
+return _tlv_bootstrap ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  set_have_as_tls=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    { echo "$as_me:$LINENO: result: $set_have_as_tls" >&5
+echo "${ECHO_T}$set_have_as_tls" >&6; }
+  ;;
+  *)
+  ;;
+esac
 if test $set_have_as_tls = yes ; then
 
 cat >>confdefs.h <<\_ACEOF
